name: Tarefa técnica
description: Infraestrutura, refatoração ou segurança.
title: ""
labels:
  - "type:infrastructure"
body:
  - type: textarea
    id: objective
    attributes:
      label: Qual é o objetivo técnico?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Como deverá ser implementado?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Quais são os critérios de aceite?
    validations:
      required: true
